[workspace]
resolver = "2"
members = ["crates/structkey", "crates/structkey-derive"]

[workspace.package]
version = "0.1.1"
authors = ["Zhang Yanpo <drdr.xp@gmail.com>"]
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/drmingdrmer/structkey"
homepage = "https://github.com/drmingdrmer/structkey"

[workspace.dependencies]
# Internal crates
structkey = { version = "0.1.1", path = "crates/structkey" }
structkey-derive = { version = "0.1.1", path = "crates/structkey-derive" }

# External
anyhow = "1"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["derive"] }
thiserror = "2"
trybuild = "1"
